// TECTAK - Teknoloji Takvimi Etkinlik Verileri
const events = [
  // --- SAVUNMA SANAYİ ---
  {
    id: 1,
    title: "SAHA EXPO Savunma Sanayi Fuarı",
    category: "savunma",
    date: "2026-10-22",
    time: "09:00",
    endTime: "18:00",
    location: "İstanbul Fuar Merkezi (İFM)",
    city: "İstanbul",
    lat: 40.9882,
    lng: 28.8251,
    description: "Uluslararası Savunma, Havacılık ve Uzay Sanayi Fuarı. Yerli ve milli savunma sanayi ürünlerinin sergilendiği dünyanın en büyük fuarlarından biri.",
    registrationUrl: "https://www.sahaexpo.com/ziyaretci-kaydi",
    type: "Fuar",
    price: "Ücretsiz",
    organizer: "SAHA İstanbul",
    registrationStatus: "open"
  },
  {
    id: 2,
    title: "IDEF Uluslararası Savunma Sanayii Fuarı",
    category: "savunma",
    date: "2026-05-18",
    time: "10:00",
    endTime: "19:00",
    location: "TÜYAP Fuar ve Kongre Merkezi",
    city: "İstanbul",
    lat: 41.0223,
    lng: 28.6192,
    description: "Türk Silahlı Kuvvetlerini Güçlendirme Vakfı öncülüğünde düzenlenen dünyanın en büyük savunma sanayii buluşmalarından biri.",
    registrationUrl: "#",
    type: "Fuar",
    price: "150 ₺",
    organizer: "TSKGV",
    registrationStatus: "closed"
  },
  {
    id: 3,
    title: "SEDEC Savunma ve Güvenlik Etkinliği",
    category: "savunma",
    date: "2026-06-24",
    time: "09:30",
    endTime: "18:00",
    location: "Ankara ATO Congresium",
    city: "Ankara",
    lat: 39.9042,
    lng: 32.8242,
    description: "Anayurt güvenliği, sınır güvenliği, iç güvenlik ve savunma tedarik zinciri odaklı fuar ve B2B buluşmaları.",
    registrationUrl: "#",
    type: "Fuar",
    price: "Ücretsiz",
    organizer: "Savunma Sanayii Başkanlığı",
    registrationStatus: "open"
  },
  {
    id: 4,
    title: "Eurasia Airshow",
    category: "savunma",
    date: "2026-08-15",
    time: "09:00",
    endTime: "17:30",
    location: "Antalya Havalimanı",
    city: "Antalya",
    lat: 36.9000,
    lng: 30.8005,
    description: "Uluslararası Havacılık ve Uzay Sanayii fuarı. Sivil ve askeri havacılık firmalarının buluşma noktası.",
    registrationUrl: "https://www.eurasiaairshow.com/register",
    type: "Fuar",
    price: "50 ₺",
    organizer: "Eurasia Airshow",
    registrationStatus: "open"
  },

  // --- TEKNOLOJİ & GENEL ---
  {
    id: 5,
    title: "TEKNOFEST Havacılık Festivali",
    category: "teknoloji",
    date: "2026-09-30",
    time: "08:00",
    endTime: "22:00",
    location: "GAP Havalimanı",
    city: "Şanlıurfa",
    lat: 37.4522,
    lng: 38.9056,
    description: "Türkiye'nin en büyük havacılık, uzay ve teknoloji festivali. Yarışmalar, uçuş gösterileri, sergi alanları ve konserler.",
    registrationUrl: "#",
    type: "Fuar",
    price: "Ücretsiz",
    organizer: "T3 Vakfı",
    registrationStatus: "open"
  },
  {
    id: 6,
    title: "Mobilefest Avrasya Teknoloji Fuarı",
    category: "teknoloji",
    date: "2026-11-05",
    time: "10:00",
    endTime: "18:00",
    location: "İstanbul Kongre Merkezi",
    city: "İstanbul",
    lat: 41.0486,
    lng: 28.9939,
    description: "İletişim teknolojileri, 5G, mobil uygulamalar ve dijital ekosistem girişimcilerini buluşturan büyük fuar.",
    registrationUrl: "#",
    type: "Fuar",
    price: "Ücretsiz",
    organizer: "Mobilefest",
    registrationStatus: "open"
  },
  {
    id: 7,
    title: "İzmir Maker Faire",
    category: "teknoloji",
    date: "2026-05-20",
    time: "11:00",
    endTime: "21:00",
    location: "İzmir Fuar Alanı, Kültürpark",
    city: "İzmir",
    lat: 38.4237,
    lng: 27.1428,
    description: "Kendin yap projeleri, 3D yazıcı gösterileri, Arduino/Raspberry Pi atölyeleri ve yenilikçi prototip sergileri.",
    registrationUrl: "https://izmir.makerfaire.com/tickets",
    type: "Fuar",
    price: "30 ₺",
    organizer: "İzmir Maker Topluluğu",
    registrationStatus: "open"
  },
  {
    id: 8,
    title: "Gaziantep Teknoloji Festivali",
    category: "teknoloji",
    date: "2026-07-25",
    time: "10:00",
    endTime: "22:00",
    location: "Gaziantep Stadyum Alanı",
    city: "Gaziantep",
    lat: 37.0662,
    lng: 37.3833,
    description: "VR/AR deneyimleri, startup showcase, coding challenge ve teknoloji konuşmaları. Güneydoğu'nun en büyük teknoloji etkinliği.",
    registrationUrl: "#",
    type: "Fuar",
    price: "40 ₺",
    organizer: "GAP Teknoloji Platformu",
    registrationStatus: "closed"
  },
  {
    id: 9,
    title: "Smart City Expo Istanbul",
    category: "teknoloji",
    date: "2026-09-15",
    time: "09:30",
    endTime: "18:00",
    location: "Dr. Mimar Kadir Topbaş Gösteri Merkezi",
    city: "İstanbul",
    lat: 40.9950,
    lng: 28.8950,
    description: "Akıllı ulaşım, temiz enerji, IoT altyapısı ve geleceğin şehir teknolojileri vizyonu.",
    registrationUrl: "#",
    type: "Seminer",
    price: "Ücretsiz",
    organizer: "İBB",
    registrationStatus: "open"
  },

  // --- BİLİŞİM & YAZILIM ---
  {
    id: 10,
    title: "Webrazzi Summit 2026",
    category: "bilisim",
    date: "2026-10-21",
    time: "08:30",
    endTime: "18:00",
    location: "Wyndham Grand Levent",
    city: "İstanbul",
    lat: 41.0805,
    lng: 29.0125,
    description: "Türkiye'nin en etkili dijital girişimcilik, yapay zeka ve teknoloji konferansı.",
    registrationUrl: "https://summit.webrazzi.com",
    type: "Seminer",
    price: "1500 ₺",
    organizer: "Webrazzi",
    registrationStatus: "open"
  },
  {
    id: 11,
    title: "DevFest Türkiye",
    category: "bilisim",
    date: "2026-08-20",
    time: "09:00",
    endTime: "19:00",
    location: "Haliç Kongre Merkezi",
    city: "İstanbul",
    lat: 41.0422,
    lng: 28.9720,
    description: "Google teknolojileri, Android, Flutter, Firebase, Cloud ve Machine Learning üzerine konuşmalar ve codelab'ler.",
    registrationUrl: "#",
    type: "Seminer",
    price: "Ücretsiz",
    organizer: "GDG İstanbul",
    registrationStatus: "closed"
  },
  {
    id: 12,
    title: "Java Day Istanbul",
    category: "bilisim",
    date: "2026-05-09",
    time: "09:00",
    endTime: "18:00",
    location: "Elite World Asia Hotel",
    city: "İstanbul",
    lat: 40.9416,
    lng: 29.1308,
    description: "Yazılım geliştiriciler için mimari, Java ekosistemi ve cloud-native uygulamalar konferansı.",
    registrationUrl: "https://javaday.istanbul/tickets",
    type: "Etkinlik",
    price: "400 ₺",
    organizer: "Istanbul Java User Group",
    registrationStatus: "closed"
  },
  {
    id: 13,
    title: "Siber Güvenlik Zirvesi (ISAF Cyber)",
    category: "bilisim",
    date: "2026-10-09",
    time: "10:00",
    endTime: "18:00",
    location: "İstanbul Fuar Merkezi",
    city: "İstanbul",
    lat: 40.9882,
    lng: 28.8251,
    description: "Penetrasyon testleri, veri koruma, bulut güvenliği ve siber istihbarat ürünleri.",
    registrationUrl: "#",
    type: "Fuar",
    price: "Ücretsiz",
    organizer: "Marmara Tanıtım",
    registrationStatus: "open"
  },
  {
    id: 14,
    title: "Bilişim Zirvesi",
    category: "bilisim",
    date: "2026-11-20",
    time: "09:00",
    endTime: "17:00",
    location: "Fişekhane, Zeytinburnu",
    city: "İstanbul",
    lat: 40.9850,
    lng: 28.9000,
    description: "Kurumsal dönüşüm, ERP, büyük veri ve yapay zeka destekli kurumsal çözümlerin tartışıldığı tepe yönetici zirvesi.",
    registrationUrl: "https://bilisimzirvesi.com.tr",
    type: "Seminer",
    price: "750 ₺",
    organizer: "BTHaber",
    registrationStatus: "open"
  },

  // --- ROBOTİK ---
  {
    id: 15,
    title: "İTÜ Robot Olimpiyatları (İTÜRO)",
    category: "robotik",
    date: "2026-05-15",
    time: "09:00",
    endTime: "19:00",
    location: "İTÜ Süleyman Demirel Kültür Merkezi",
    city: "İstanbul",
    lat: 41.1058,
    lng: 29.0232,
    description: "Çizgi izleyen, mini sumo, arazi ve serbest kategori robot yarışmaları. Türkiye'nin en eski robot olimpiyatı.",
    registrationUrl: "#",
    type: "Gösteri",
    price: "Ücretsiz",
    organizer: "İTÜ OTOK",
    registrationStatus: "closed"
  },
  {
    id: 16,
    title: "MEB Uluslararası Robot Yarışması",
    category: "robotik",
    date: "2026-06-12",
    time: "10:00",
    endTime: "18:00",
    location: "Atatürk Spor Salonu",
    city: "Erzurum",
    lat: 39.9080,
    lng: 41.2760,
    description: "Mesleki ve teknik eğitim öğrencilerinin yanı sıra üniversite öğrencilerinin tasarladığı robotların kıyasıya mücadelesi.",
    registrationUrl: "http://robot.meb.gov.tr",
    type: "Gösteri",
    price: "Ücretsiz",
    organizer: "Milli Eğitim Bakanlığı",
    registrationStatus: "open"
  },
  {
    id: 17,
    title: "ODTÜ Robot Günleri",
    category: "robotik",
    date: "2026-07-02",
    time: "09:30",
    endTime: "17:30",
    location: "ODTÜ KKM",
    city: "Ankara",
    lat: 39.8908,
    lng: 32.7838,
    description: "Otonom robotlar, drone gösterileri ve robotik kodlama atölyeleri.",
    registrationUrl: "https://robot.metu.edu.tr",
    type: "Etkinlik",
    price: "Ücretsiz",
    organizer: "ODTÜ Robot Topluluğu",
    registrationStatus: "open"
  },
  {
    id: 18,
    title: "Bursa Drone Şampiyonası",
    category: "robotik",
    date: "2026-06-10",
    time: "14:00",
    endTime: "20:00",
    location: "Bursa Atatürk Stadyumu Çevresi",
    city: "Bursa",
    lat: 40.1956,
    lng: 29.0601,
    description: "FPV drone yarışları, kargo drone demoları ve otonom uçuş gösterileri. Ödüllü yarışmalar.",
    registrationUrl: "#",
    type: "Gösteri",
    price: "25 ₺",
    organizer: "Türkiye Drone Ligi",
    registrationStatus: "open"
  },

  // --- ELEKTRİK-ELEKTRONİK & ENDÜSTRİ ---
  {
    id: 19,
    title: "WIN EURASIA Endüstri Fuarı",
    category: "elektrik-elektronik",
    date: "2026-06-10",
    time: "10:00",
    endTime: "18:00",
    location: "İstanbul Fuar Merkezi (İFM)",
    city: "İstanbul",
    lat: 40.9882,
    lng: 28.8251,
    description: "Otomasyon, lojistik, kaynak ve enerji teknolojileri alanındaki en büyük Avrasya sanayi fuarı.",
    registrationUrl: "https://win-eurasia.com/tr/ziyaretci-kaydi",
    type: "Fuar",
    price: "Ücretsiz",
    organizer: "Hannover Fairs Turkey",
    registrationStatus: "open"
  },
  {
    id: 20,
    title: "Wenergy Temiz Enerji Fuarı",
    category: "elektrik-elektronik",
    date: "2026-05-22",
    time: "09:30",
    endTime: "18:00",
    location: "Fuar İzmir",
    city: "İzmir",
    lat: 38.3245,
    lng: 27.1425,
    description: "Güneş, rüzgar enerjisi sistemleri, elektrikli araç şarj istasyonları ve enerji depolama çözümleri.",
    registrationUrl: "#",
    type: "Fuar",
    price: "Ücretsiz",
    organizer: "İZFAŞ",
    registrationStatus: "closed"
  },
  {
    id: 21,
    title: "Sign Istanbul",
    category: "elektrik-elektronik",
    date: "2026-09-23",
    time: "10:00",
    endTime: "18:00",
    location: "TÜYAP Fuar Merkezi",
    city: "İstanbul",
    lat: 41.0223,
    lng: 28.6192,
    description: "Endüstriyel LED ekranlar, dijital baskı makineleri, lazer CNC teknolojileri ve aydınlatma sistemleri.",
    registrationUrl: "#",
    type: "Fuar",
    price: "50 ₺",
    organizer: "Tarsus Turkey",
    registrationStatus: "open"
  },
  {
    id: 22,
    title: "Elektrik-Elektronik Mühendisliği Fuarı",
    category: "elektrik-elektronik",
    date: "2026-06-02",
    time: "09:00",
    endTime: "19:00",
    location: "TÜYAP Fuar Merkezi",
    city: "İstanbul",
    lat: 41.0223,
    lng: 28.6192,
    description: "Endüstriyel otomasyon, güç elektroniği, yenilenebilir enerji sistemleri ve IoT çözümleri sergisi.",
    registrationUrl: "#",
    type: "Fuar",
    price: "75 ₺",
    organizer: "EMO",
    registrationStatus: "open"
  }
];

// Kategori tanımları
const categories = [
  { id: "tumu", label: "Tümü", icon: "📋" },
  { id: "teknoloji", label: "Teknoloji", icon: "💻" },
  { id: "bilisim", label: "Bilişim", icon: "🌐" },
  { id: "robotik", label: "Robotik", icon: "🤖" },
  { id: "savunma", label: "Savunma Sanayi", icon: "🛡️" },
  { id: "elektrik-elektronik", label: "Elektrik-Elektronik", icon: "⚡" }
];

// Etkinlik tipi renkleri
const typeColors = {
  "Seminer": "#00D4FF",
  "Fuar": "#00FF88",
  "Gösteri": "#FF6B6B",
  "Etkinlik": "#FFD93D"
};
